# docker-compose up --build 重新构建
version: '3.8'
services:
  my-tomcat:
    build: .
    image: my-tomcat:1.0
    depends_on:
      - redis
    ports:
    - "8080":"8080"
  redis:
    image: "library/redis:alpine"